version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`maillet.bzh`)"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=4321"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.csp-headers.headers.customResponseHeaders.Content-Security-Policy=script-src 'self' 'unsafe-inline' data: https://cdn.jsdelivr.net https://www.google.com https://www.gstatic.com https://analytics.maillet.bzh; object-src 'none'; base-uri 'self';"
      - "traefik.http.routers.portfolio.middlewares=csp-headers@docker"

networks:
  traefik:
    external: true
