version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`maillet.bzh`)"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=4321"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
